from shop.models import Item, Purchase
items = Item.objects.all()
item_1 = Item(name="Xiaomi",price=33000)
item_1.save()
item_2 = Item(name="iPhone 14",price=88000)
item_2.save()
item_3 = Item(name="Lenovo ThinkPad T480",price=33000)
item_3.save()
item_4 = Item(name="Samsung TV 55",price=110000)
item_4.save()
item_5 = Item(name="Samsung Z fold 4",price=33000)
item_5.save()

purchases = Purchase.objects.all()
purchase_1 = Purchase(id=None, name="Ruslan", age=18, item=item_1)
purchase_1.save()
purchase_2 = Purchase(id=None, name="Nursultan", age=16, item=item_2)
purchase_2.save()
purchase_3 = Purchase(id=None, name="Vasya Pupkin", age=20, item=item_3)
purchase_3.save()
purchase_4 = Purchase(id=None, name="Ivan Ivanov", age=30, item=item_4)
purchase_4.save()
purchase_5= Purchase(id=None, name="Bekobolot", age=22, item=item_5)
purchase_5.save()

exit()
