# Generated by Django 3.2 on 2023-03-03 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Пожалуйста выберите категорию продукта', on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Укажите дату покупки продукта', verbose_name='Дата покупки продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Пожалуйста укажите имя продукта', max_length=30, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='Цена указана в сомах', verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_status',
            field=models.BooleanField(choices=[(True, 'Продан'), (False, 'Не продан'), (False, 'Зарезервирован'), (False, 'На складе'), (False, 'Товар в пути')], default=False, help_text='Пожалуйста выберите статус продуката'),
        ),
    ]
